version: '3.5'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13-alpine@sha256:88a45f9e328549b2579256c46ee38e5c0e25ae58303d9eb6d9c7ed8d6d2bbf3c
    container_name: clickhouse
    hostname: clickhouse
    privileged: true
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/public:/csv_files
      - ./docker-compose/docker-entrypoint-initdb.d/00_initial_datasets_tables.sh:/docker-entrypoint-initdb.d/00_initial_datasets_tables.sh
#    entrypoint: /bin/sh -c "chmod +x /docker-entrypoint-initdb.d/00_initial_datasets_tables.sh && /entrypoint.sh"
#
#  solution:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: solution
#    volumes:
#      - ./app:/app/app/
#      - ./main.py:/app/main.py
#    depends_on:
#      - clickhouse
#    #    stdin_open: true
#    #    tty: true
#
#    command: /bin/sh -c "sleep 42 && python3 -u /app/main.py"
#    command: [ 'python3', '-u', 'app/main.py' ]
